version: "3.8"

services:
  keycloak-db:
    image: postgres:15
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    networks:
      - oauth-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: ${KEYCLOAK_CONTAINER_NAME}
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL_HOST: ${POSTGRES_HOST}
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: ${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME}
    ports:
      - "${KEYCLOAK_PORT}:8080"
    volumes:
      - ${KEYCLOAK_THEME_PATH}:/opt/keycloak/themes/${KEYCLOAK_THEME_NAME}
    depends_on:
      - keycloak-db
    networks:
      - oauth-network

  keycloak-config-cli:
    image: adorsys/keycloak-config-cli:latest
    container_name: keycloak-config-cli
    environment:
      KEYCLOAK_URL: http://${KEYCLOAK_CONTAINER_NAME}:8080
      KEYCLOAK_USER: ${KEYCLOAK_ADMIN}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - ./keycloak-config:/config
    depends_on:
      - keycloak
    networks:
      - oauth-network

  blog-service:
    image: ${BLOG_SERVICE_IMAGE}
    container_name: ${BLOG_CONTAINER_NAME}
    environment:
      RUST_LOG: info
      KEYCLOAK_URL: http://${KEYCLOAK_CONTAINER_NAME}:8080
      JWT_ISSUER: http://${KEYCLOAK_CONTAINER_NAME}:8080/realms/blog-realm
      JWKS_URL: http://${KEYCLOAK_CONTAINER_NAME}:8080/realms/blog-realm/protocol/openid-connect/certs
    expose:
      - "${BLOG_SERVICE_PORT}"
    depends_on:
      - keycloak
      - keycloak-config-cli
    networks:
      - oauth-network

  nginx:
    image: nginx:latest
    container_name: ${NGINX_CONTAINER_NAME}
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - blog-service
      - keycloak
    networks:
      - oauth-network

networks:
  oauth-network:
    driver: bridge
