name: ci-backend

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  rust-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Run cargo fmt check
        working-directory: backend
        run: cargo fmt --check

      - name: Run cargo clippy
        working-directory: backend
        run: cargo clippy -- -D warnings
